/**
 * Web3 and Contract Initialization Utilities
 */

export async function getWeb3() {
  if (typeof window.Web3 === "undefined") {
    throw new Error("Web3 library not loaded. Check internet connection or node_modules.");
  }
  // Connect directly to local Ganache RPC
  const provider = new window.Web3.providers.HttpProvider("http://127.0.0.1:7545");
  const web3 = new window.Web3(provider);
  return web3;
}

export async function getContract(web3) {
  // Fetch the compiled artifact generated by truffle compile
  const response = await fetch("./src/contracts/CertVerify.json");
  if (!response.ok) {
    throw new Error("Could not load CertVerify.json artifact. Run truffle compile / migrate first.");
  }
  const certVerifyArtifact = await response.json();
  const networkId = await web3.eth.net.getId();
  const deployedNetwork = certVerifyArtifact.networks[networkId];

  if (!deployedNetwork || !deployedNetwork.address) {
    throw new Error(
      `CertVerify contract not deployed on network ${networkId}. Run: truffle migrate --network development`
    );
  }

  const contract = new web3.eth.Contract(
    certVerifyArtifact.abi,
    deployedNetwork.address
  );

  return { contract, address: deployedNetwork.address };
}

export async function getCurrentAccount(web3) {
  const accounts = await web3.eth.getAccounts();
  if (!accounts || accounts.length === 0) {
    throw new Error("No accounts found on Ganache. Is Ganache running on port 7545?");
  }
  return accounts[0]; // deployer / first issuer
}
